This is makeindex, version 2.15 [MiKTeX 21.3].
Scanning style file ./Relatorio-DEE.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Relatorio-DEE.acn....done (87 entries accepted, 0 rejected).
Sorting entries....done (632 comparisons).
Generating output file Relatorio-DEE.acr....done (92 lines written, 0 warnings).
Output written in Relatorio-DEE.acr.
Transcript written in Relatorio-DEE.alg.
